name:                advent2022
version:             0.1.0.0
github:              "cjlarose/advent-2022"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Chris LaRose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cjlarose/advent-2022#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- filepath
- megaparsec
- mtl
- parser-combinators
- tasty
- tasty-golden
- text

library:
  source-dirs: src

executables:
  advent2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2022

tests:
  advent2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2022
